home:
    path: /
    controller: Internship\Controller\HomeController::index
    methods: [GET]
    defaults:
        template: 'home/index.html.twig'
products:
    path: /products
    controller: Internship\Controller\HomeController::products
    methods: [GET]
    defaults:
        template: 'products/product_list.html.twig'
product:
    path: /product/{id}
    controller: Internship\Controller\HomeController::product
    methods: [GET]
    defaults:
        template: 'products/product.html.twig'
addProduct:
    path: /new
    controller: Internship\Controller\AdminController::addProduct
    methods: [GET, POST]
    defaults:
        template: 'admin/add_product.html.twig'
editProduct:
    path: /edit/{id}
    controller: Internship\Controller\AdminController::editProduct
    methods: [GET, POST]
    defaults:
        template: 'admin/edit_product.html.twig'
deleteProduct:
    path: /{id}
    controller: Internship\Controller\AdminController::deleteProduct
    methods: [DELETE]
orders:
    path: /orders
    controller: Internship\Controller\HomeController::orders
    methods: [GET]
    defaults:
        template: 'orders/order_list.html.twig'
order:
    path: /order/{id}
    controller: Internship\Controller\HomeController::order
    methods: [GET]
    defaults:
        template: 'orders/order.html.twig'
cart:
    path: /cart
    controller: Internship\Controller\HomeController::cart
    defaults:
        template: 'home/cart.html.twig'
contact:
    path: /contact
    controller: Internship\Controller\ContactController::contact
    methods: [GET, POST]
    defaults:
        template: 'contact/contact.html.twig'
messages:
    path: /messages
    controller: Internship\Controller\AdminController::messages
    methods: [GET]
    defaults:
        template: 'admin/message.html.twig'
login:
    path: /login
    controller: Internship\Controller\SecurityController::login
    defaults:
        template: 'security/login.html.twig'
logout:
    path: /logout
    controller: Internship\Controller\SecurityController::logout
signup:
    path: /signup
    controller: Internship\Controller\RegistrationController::register
    defaults:
        template: 'registration/register.html.twig'