home:
    path: /
    controller: Internship\Controller\HomeController::index
    methods: [GET]
    defaults:
        template: 'home/index.html.twig'
products:
    path: /products
    controller: Internship\Controller\HomeController::products
    methods: [GET]
    defaults:
        template: 'products/product_list.html.twig'
product:
    path: /product/{id}
    controller: Internship\Controller\HomeController::product
    methods: [GET]
    defaults:
        template: 'products/product_item.html.twig'
orders:
    path: /orders
    controller: Internship\Controller\HomeController::orders
    methods: [GET]
    defaults:
        template: 'orders/order_list.html.twig'
order:
    path: /order/{id}
    controller: Internship\Controller\HomeController::order
    methods: [GET]
    defaults:
        template: 'orders/order_list.html.twig'
orderlines:
    path: /orderlines/{id}
    controller: Internship\Controller\HomeController::orderline
    methods: [GET]
    defaults:
        template: 'orders/order_item.html.twig'
cart:
    path: /cart
    controller: Internship\Controller\HomeController::cart
    defaults:
        template: 'home/cart.html.twig'
contacts:
    path: /contacts
    controller: Internship\Controller\HomeController::messages
    defaults:
        template: 'home/contacts.html.twig'
login:
    path: /login
    controller: Internship\Controller\HomeController::login
    defaults:
        template: 'home/login.html.twig'
signup:
    path: /signup
    controller: Internship\Controller\HomeController::signUp
    defaults:
        template: 'home/sign_up.html.twig'