home:
    path: /
    controller: Internship\Controller\HomeController::index
    methods: [GET]
    defaults:
        template: 'home/index.html.twig'
products:
    path: /products
    controller: Internship\Controller\HomeController::products
    methods: [GET]
    defaults:
        template: 'products/product_list.html.twig'
product:
    path: /product/{id}
    controller: Internship\Controller\HomeController::product
    methods: [GET]
    defaults:
        template: 'products/product.html.twig'
addProduct:
    path: /new
    controller: Internship\Controller\AdminController::addProduct
    methods: [GET]
    defaults:
        template: 'admin/add_product.html.twig'
orders:
    path: /orders
    controller: Internship\Controller\HomeController::orders
    methods: [GET]
    defaults:
        template: 'orders/order_list.html.twig'
order:
    path: /order/{id}
    controller: Internship\Controller\HomeController::order
    methods: [GET]
    defaults:
        template: 'orders/order.html.twig'
cart:
    path: /cart
    controller: Internship\Controller\HomeController::cart
    defaults:
        template: 'home/cart.html.twig'
contacts:
    path: /contacts
    controller: Internship\Controller\HomeController::messages
    methods: [GET]
    defaults:
        template: 'home/contacts.html.twig'
messages:
    path: /messages
    controller: Internship\Controller\HomeController::messages
    methods: [GET]
    defaults:
        template: 'home/messages.html.twig'
login:
    path: /login
    controller: Internship\Controller\SecurityController::login
    defaults:
        template: 'security/login.html.twig'
logout:
    path: /logout
    controller: Internship\Controller\SecurityController::logout
signup:
    path: /signup
    controller: Internship\Controller\RegistrationController::register
    defaults:
        template: 'registration/register.html.twig'